"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange)\
$os\
$shell\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$kubernetes\
[](fg:color_blue bg:color_bg3)\
$nix_shell\
$docker_context\
[](fg:color_bg3 bg:color_bg1)\
$cmd_duration\
[ ](fg:color_bg1)\
$line_break$status$character"""

palette = 'gruvbox_dark'

[shell]
disabled = false
style = "bg:color_orange fg:color_fg0"
format = '[ $indicator ]($style)'
bash_indicator = "bash"
nu_indicator = "nu"
pwsh_indicator = "pwsh"
fish_indicator = "fish"

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = true

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncate_to_repo = true
truncation_length = 3
truncation_symbol = ""

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[cmd_duration]
min_time = 2000
style = "bg:color_bg1"
format = '[[  $duration ](fg:color_fg0 bg:color_bg1)]($style)'

[status]
disabled = false
symbol = ""

[time]
disabled = true
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[kubernetes]
disabled = false
style = "bg:color_blue"
format = '[[ $symbol( $context) ](fg:color_fg0 bg:color_blue)]($style)'

[hostname]
disabled = false
style = "bg:color_orange fg:color_fg0"

[nix_shell]
disabled = false
style = "bg:color_bg3"
format = '[[ (nix-$name )](fg:#83a598 bg:color_bg3)]($style)'